/* This file is auto-generated by the ScriptDirectedGui program.                  */
/* Please do not modify directly as the code cannot then be guaranteed to operate */
/* correctly. However, please feel free to copy the source into a project.        */

package com.thehutgroup.createdgui;

import com.thehutgroup.guicomponents.FreeButton;
import com.thehutgroup.guicomponents.FreeLabel;
import com.thehutgroup.guicomponents.FreeLabelTextButtonTriple;
import com.thehutgroup.messages.MessageHandler;
import com.thehutgroup.utilities.FileUtilities;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.commons.lang.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;

public class CopyGuiDialog extends JFrame {

    private static final String SUB_HEADING = " - Copy GUI to Java Project";
    private static String TITLE;
    private static final int FRAME_X_SIZE = 700;
    private static final int FRAME_Y_SIZE = 250;
    private Color col = new Color(230, 255, 255);

    private CopyGuiDialog tg = this;

    private MainGui mainGui;

    private MessageHandler messageHandler;

    @Autowired
    public CopyGuiDialog(MainGui mainGui, MessageHandler messageHandler) {

        TITLE = messageHandler.getMessage("constants.mainheading") + SUB_HEADING;

        this.mainGui = mainGui;
        this.mainGui.setEnabled(false);
        this.setTitle(TITLE);
        this.setSize(FRAME_X_SIZE, FRAME_Y_SIZE);

        JPanel p1 = new JPanel();
        p1.setLayout(null);
        p1.setBackground(col);

        FreeLabel l0 = new FreeLabel(messageHandler.getMessage("constants.mainheading"), 30, 30, 500, 30, new Font("", Font.BOLD + Font.ITALIC, 20));

        FreeButton b0 = new FreeButton("OK", 255, 150, 80);

        FreeButton b1 = new FreeButton("Cancel", 365, 150, 80);


        FreeLabelTextButtonTriple comp0 = new FreeLabelTextButtonTriple(col, "Please enter location of service:", 30, 90, 10, "Browse");

        // This is the control for the OK button
        b0.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (!StringUtils.isEmpty(comp0.getText())) {
                    String src = "C:/GradleTutorials/TestGuiRunner/src/main/java/com/thehutgroup/testgui/TestGui.java";
                    String targ = "C:/GradleTutorials/" + comp0.getText() + "/src/main/java/com/thehutgroup/createdgui/TestGui.java";
                    try {
                        FileUtilities.fileCopy(src, targ);
                    } catch (IOException e1) {
                        e1.printStackTrace();
                    }
                    JOptionPane.showMessageDialog(tg, "The new GUI has been successfully copied to project " + comp0.getText(),
                        TITLE, JOptionPane.INFORMATION_MESSAGE);
                    b1.doClick();
                }  else {
                    JOptionPane.showMessageDialog(tg, "No project selected - please enter/select a project before continuing",
                        TITLE, JOptionPane.INFORMATION_MESSAGE);
                }
            }
        });

        // This is the control for the Cancel-implement button
        b1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                mainGui.setEnabled(true);
                tg.dispose();
            }
        });

        // This is the control for the Browse button on the triple Label, Text, Button
        comp0.getButton().addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                JFileChooser fc = new JFileChooser();
                fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                fc.setCurrentDirectory(new File("C:/GradleTutorials"));
                int returnVal = fc.showDialog(tg, "Select");
                if (returnVal == 0) {
                    comp0.setText(fc.getSelectedFile().getName());
                }
            }
        });

        p1.add(b0);
        p1.add(b1);
        p1.add(comp0.getPanel());
        p1.add(l0);
        this.add(p1);
    }
}
