/* This file is auto-generated by the ScriptDirectedGui program.                  */
/* Please do not modify directly as the code cannot then be guaranteed to operate */
/* correctly. However, please feel free to copy the source into a project.        */

package com.thehutgroup.createdgui;

import com.thehutgroup.guicomponents.FreeButton;
import com.thehutgroup.guicomponents.FreeLabel;
import com.thehutgroup.guicomponents.FreeLabelTextButtonTriple;
import com.thehutgroup.messages.MessageHandler;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.springframework.beans.factory.annotation.Autowired;

public class CopyGuiDialog extends JFrame {

    private static final String SUB_HEADING = " - Copy GUI to Java Project";
    private static String TITLE;
    private static final int FRAME_X_SIZE = 700;
    private static final int FRAME_Y_SIZE = 250;
    private Color col = new Color(230, 255, 255);

    private CopyGuiDialog tg = this;

    private MainGui mainGui;

    private MessageHandler messageHandler;

    @Autowired
    public CopyGuiDialog(MainGui mainGui, MessageHandler messageHandler) {

        TITLE = messageHandler.getMessage("constants.mainheading") + SUB_HEADING;

        this.mainGui = mainGui;
        this.mainGui.setEnabled(false);
        this.setTitle(TITLE);
        this.setSize(FRAME_X_SIZE, FRAME_Y_SIZE);

        JPanel p1 = new JPanel();
        p1.setLayout(null);
        p1.setBackground(col);

        FreeLabel l0 = new FreeLabel(messageHandler.getMessage("constants.mainheading"), 30, 30, 500, 30, new Font("", Font.BOLD + Font.ITALIC, 20));

        FreeButton b0 = new FreeButton("OK", 255, 150, 80);

        FreeButton b1 = new FreeButton("Cancel", 365, 150, 80);


        FreeLabelTextButtonTriple comp0 = new FreeLabelTextButtonTriple(col, "Please enter location of service:", 30, 90, 10, "Browse");

        // This is the control for the OK button
        b0.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                b1.doClick();
            }
        });

        // This is the control for the Cancel-implement button
        b1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                mainGui.setEnabled(true);
                tg.dispose();
            }
        });

        // This is the control for the Browse button on the triple Label, Text, Button
        comp0.getButton().addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                System.out.println("Button - " + comp0.getButtonText() + " in the triple group has been clicked");
            }
        });

        p1.add(b0);
        p1.add(b1);
        p1.add(comp0.getPanel());
        p1.add(l0);
        this.add(p1);
    }
}
